# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

  release:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install


      - name: Compile executable
        run: |
          deno compile --no-check --allow-env --target x86_64-pc-windows-msvc --output dist/x86_64-pc-windows-msvc src/main.ts
          deno compile --no-check --allow-env --target x86_64-apple-darwin --output dist/x86_64-apple-darwin src/main.ts
          deno compile --no-check --allow-env --target aarch64-apple-darwin --output dist/aarch64-apple-darwin src/main.ts
          deno compile --no-check --allow-env --target x86_64-unknown-linux-gnu --output dist/x86_64-unknown-linux-gnu src/main.ts
          deno compile --no-check --allow-env --target aarch64-unknown-linux-gnu --output dist/aarch64-unknown-linux-gnu src/main.ts

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: deno run -A npm:semantic-release
